name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk -pdf -interaction=nonstopmode -halt-on-error "CV - Lorenzo Gardini.tex"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-lorenzo-gardini
          path: "*.pdf"
